### ISSUE TITLE
Yeoman generator

### ISSUE THREAD

**Issue by jaumard** [athombv/node-athom-cli#29]
Hi guys! 

I just create a yeoman generator (https://github.com/jaumard/generator-homey) that allow user to have more options and allow basic generation for drivers too. 

Are you interested by integrate it into this module ? I can make a PR that do this.

If not just close this issue :)

Thanks

**Comment by WeeJeWel** [comment]
Brilliant! I'd rather not merge it because it has to be maintained, but I'm thinking of making a list of community tools on the Athom Developer website. I'll gladly link to this project!

By the way, I've spotted an error in the generated app.json: `"permissions": [&#39;homey:manager:geolocation&#39;, &#39;homey:manager:ledring&#39;]`

**Comment by jaumard** [comment]
Thanks! I'll fix it and add tests for this ^^ 
My idea was to add it as a dependency and use it in place of yours, I don't mind maintain it :) as you want.

Good idea for the community list :D

**Comment by WeeJeWel** [comment]
As promised! https://developers.athom.com/library/community/

**Comment by jaumard** [comment]
Perfect ! Thanks !! I fix the permissions problem :) all should work now !
